name: Check typos

on:
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  check-typos:
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check for typos
        uses: crate-ci/typos@v1.28.4
